---
- name: Créer et configurer les Virtual Hosts
  hosts: localhost
  become: yes
  tasks:
    - name: Créer le dossier du Virtual Host
      file:
        path: "/var/www/{{ item.name }}"
        state: directory
        owner: www-data
        group: www-data
        mode: 0755
      loop:
        - { name: "www.hei.school" }
        - { name: "api.hei.school" }
        - { name: "front.hei.school" }
        - { name: "back.hei.school" }
       

    - name: Copier le fichier de configuration du Virtual Host
      template:
        src: /virtualhost.conf.j2
        dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
        owner: root
        group: root
        mode: 0644
      loop:
        - { name: "www.hei.school" }
        - { name: "api.hei.school" }
        - { name: "front.hei.school" }
        - { name: "back.hei.school" }

    - name: Vérifier si le Virtual Host est activé
      stat:
        path: "/etc/apache2/sites-enabled/{{ item.name }}.conf"
      loop:
        - { name: "www.hei.school" }
        - { name: "api.hei.school" }
        - { name: "front.hei.school" }
        - { name: "back.hei.school" }
      register: vh_enabled
      changed_when: false

    - name: Activer le Virtual Host
      command: a2ensite {{ item.name }}.conf
      loop:
        - { name: "www.hei.school" }
        - { name: "api.hei.school" }
        - { name: "front.hei.school" }
        - { name: "back.hei.school" }
      notify:
        - Redémarrer Apache
      when: not vh_enabled.stat.exists

    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted
